Repository CoinChums/CoinChums, pull requests merged in 2024-02, with the labels that each got.

#28 Feat/input component
  src/components/Badge/Badge.tsx
  src/components/Blocks/Blocks.tsx
  src/components/Button/Button.tsx
  src/components/Button/types.ts
  src/components/ErrorScreen/ErrorScreen.tsx
  src/components/ExpenseTree/ExpenseTree.tsx
  src/components/GroupListTile/GroupListTile.tsx
  src/components/Header/Header.tsx
  src/components/ImageRender/Image.tsx
  src/components/Indicator/Indicator.tsx
  src/components/Input/Input.tsx
  src/components/Input/styles.ts
  src/components/Input/types.ts
  src/components/Modal/Modal.tsx
  src/components/index.ts
  src/models/expense.ts
  src/screens/Home/Home.tsx
  src/screens/Onboarding/Onboarding.tsx
  src/screens/Onboarding/components/Card.tsx
  src/screens/Settings/Settings.tsx
  src/themes/typography.ts
Labels: WIP

#21 Component: Payer Tiles
  scripts/generateScreens.js
  src/assets/images/bill.svg
  src/components/Input/styles.ts
  src/components/PayerTiles/PayerTiles.tsx
  src/components/PayerTiles/styles.ts
  src/components/PayerTiles/types.ts
  src/components/index.ts
  src/screens/Home/Home.tsx
Labels: READY TO MERGE, DEV TESTED

#9 feat: Jest test cases
  .eslintrc.js
  .gitignore
  .prettierrc.js
  __mocks__/ImageMock.js
  __mocks__/SvgMock.js
  __mocks__/globalMock.js
  __tests__/App.test.tsx
  __tests__/screens/home.test.js
  index.js
  ios/Podfile.lock
  jest.config.js
  jest.setup.js
  package.json
  src/App.tsx
  src/navigation/AppStack.tsx
  src/navigation/AuthStack.tsx
  src/screens/NetworkLogger/NetworkLogger.tsx
  src/screens/index.ts
  tsconfig.json
  yarn.lock
Labels: READY TO MERGE, DEV TESTED

#13 feat: Firebase Auth
  android/app/build.gradle
  android/app/google-services.json
  debug.keystore
  package.json
  src/constants/enums.ts
  src/navigation/AuthStack.tsx
  src/navigation/index.tsx
  src/screens/Authentication/Authentication.style.ts
  src/screens/Authentication/Authentication.tsx
  src/screens/Launch/Launch.tsx
  src/screens/index.ts
  src/types/types.ts
  yarn.lock
Labels: WIP, DO NOT MERGE

#29 README Update
  CONTRIBUTING.md
  README.md
  SETUP.md
Labels: READY TO MERGE, DEV TESTED

#34 migrate state management to zustand
  package.json
  src/App.tsx
  src/actions/auth.ts
  src/components/GroupListTile/types.ts
  src/constants/enums.ts
  src/navigation/index.tsx
  src/redux/login/login.selector.ts
  src/redux/login/login.store.ts
  src/redux/login/saga/login.actions.ts
  src/redux/login/saga/login.saga.ts
  src/redux/login/types.ts
  src/redux/reduxStore.ts
  src/redux/rootReducer.ts
  src/redux/rootSaga.ts
  src/screens/Authentication/Authentication.tsx
  src/store/useAuth/useAuth.tsx
  src/store/useAuth/useAuth.types.ts
  src/types/models/expense.ts
  src/types/models/user.ts
  yarn.lock
Labels: READY TO MERGE

#36 chore: Firebase removed
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/CarPool.xcodeproj/project.pbxproj
  ios/CarPool/AppDelegate.mm
  ios/Podfile.lock
  package.json
  src/screens/Authentication/Authentication.tsx
  yarn.lock
Labels: READY TO MERGE, DEV TESTED
